# Generated by Django 5.2.5 on 2025-08-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_label_remove_reportedquestion_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='explanations/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text="Use labels for question banks, e.g., 'Previous Year 2023'", to='api.label'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Duration of the quiz in minutes.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('PRACTICE', 'Practice'), ('MODEL_TEST', 'Model Test'), ('QUESTION_BANK', 'Question Bank')], default='PRACTICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='selected_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer'),
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="User's reason for reporting the question.")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
