# Generated by Django 5.2.5 on 2025-08-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answer_image_question_explanation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearQuiz',
            fields=[
            ],
            options={
                'verbose_name': 'Previous Year Quiz',
                'verbose_name_plural': 'Previous Year Quizzes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.quiz',),
        ),
    ]
