# Generated by Django 5.2.5 on 2025-08-22 09:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quizcategory_quiz_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('QUESTION_ANSWERED', 'Question Answered'), ('QUIZ_COMPLETED', 'Quiz Completed'), ('MODEL_TEST_COMPLETED', 'Model Test Completed'), ('PRACTICE_SESSION', 'Practice Session')], max_length=30)),
                ('activity_date', models.DateField(auto_now_add=True)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration of activity in minutes', null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.quizattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-activity_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('QUESTIONS_SOLVED', 'Questions Solved'), ('MODEL_TESTS_TAKEN', 'Model Tests Taken'), ('PRACTICE_TIME_MINUTES', 'Practice Time (Minutes)'), ('QUIZ_ATTEMPTS', 'Quiz Attempts')], max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('target_value', models.PositiveIntegerField(help_text='Target value for this date')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Progress',
                'verbose_name_plural': 'Daily Progress',
                'ordering': ['-date', 'target_type'],
                'unique_together': {('user', 'target_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('QUESTIONS_SOLVED', 'Questions Solved'), ('MODEL_TESTS_TAKEN', 'Model Tests Taken'), ('PRACTICE_TIME_MINUTES', 'Practice Time (Minutes)'), ('QUIZ_ATTEMPTS', 'Quiz Attempts')], max_length=30)),
                ('target_value', models.PositiveIntegerField(help_text='Target value (e.g., 50 questions, 2 tests, 120 minutes)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Target',
                'verbose_name_plural': 'Daily Targets',
                'unique_together': {('user', 'target_type')},
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('QUESTIONS_SOLVED', 'Questions Solved'), ('MODEL_TESTS_TAKEN', 'Model Tests Taken'), ('PRACTICE_TIME_MINUTES', 'Practice Time (Minutes)'), ('QUIZ_ATTEMPTS', 'Quiz Attempts')], max_length=30)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Streak',
                'verbose_name_plural': 'Streaks',
                'unique_together': {('user', 'target_type')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('target_type', models.CharField(choices=[('QUESTIONS_SOLVED', 'Questions Solved'), ('MODEL_TESTS_TAKEN', 'Model Tests Taken'), ('PRACTICE_TIME_MINUTES', 'Practice Time (Minutes)'), ('QUIZ_ATTEMPTS', 'Quiz Attempts')], max_length=30)),
                ('total_target', models.PositiveIntegerField(default=0)),
                ('total_achieved', models.PositiveIntegerField(default=0)),
                ('days_completed', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Progress',
                'verbose_name_plural': 'Weekly Progress',
                'ordering': ['-week_start_date', 'target_type'],
                'unique_together': {('user', 'week_start_date', 'target_type')},
            },
        ),
    ]
