# Generated by Django 5.2.5 on 2025-08-22 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_useractivity_dailyprogress_dailytarget_streak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('total_questions_answered', models.PositiveIntegerField(default=0)),
                ('total_quizzes_completed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Guest User',
                'verbose_name_plural': 'Guest Users',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailytarget',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='savedquestion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='streak',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailytarget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='savedquestion',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='streak',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to='api.guestuser'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='daily_progress_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='daily_progress_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'target_type', 'date'), name='unique_user_target_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'target_type', 'date'), name='unique_guest_target_date'),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='daily_target_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='daily_target_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'target_type'), name='unique_user_target_type'),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'target_type'), name='unique_guest_target_type'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='quiz_attempt_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='quiz_attempt_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='saved_question_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='saved_question_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'question'), name='unique_user_question'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'question'), name='unique_guest_question'),
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='streak_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='streak_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'target_type'), name='unique_user_streak_type'),
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'target_type'), name='unique_guest_streak_type'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='user_activity_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='user_activity_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='weekly_progress_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='weekly_progress_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'week_start_date', 'target_type'), name='unique_user_week_target'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'week_start_date', 'target_type'), name='unique_guest_week_target'),
        ),
    ]
