# Generated by Django 5.2.5 on 2026-07-14 18:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_guestuser_alter_dailyprogress_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTestTemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('include_subcategories', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'category__name'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_mark',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generated_for_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_quizzes', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generated_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='unanswered_mark',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='wrong_mark',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ModelTestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('correct_mark', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('wrong_mark', models.DecimalField(decimal_places=2, default=Decimal('-0.25'), max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('0'))])),
                ('unanswered_mark', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='mtt_duration_positive'), models.CheckConstraint(condition=models.Q(('correct_mark__gte', 0)), name='mtt_correct_nonnegative'), models.CheckConstraint(condition=models.Q(('wrong_mark__lte', 0)), name='mtt_wrong_nonpositive'), models.CheckConstraint(condition=models.Q(('unanswered_mark__lte', 0)), name='mtt_unanswered_nonpositive')],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_quizzes', to='api.modeltesttemplate'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('generated_for_user__isnull', False), ('generated_for_guest__isnull', False), _negated=True), name='quiz_generated_owner_not_both'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('correct_mark__gte', 0)), name='quiz_correct_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('wrong_mark__lte', 0)), name='quiz_wrong_nonpositive'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('unanswered_mark__lte', 0)), name='quiz_unanswered_nonpositive'),
        ),
        migrations.AddField(
            model_name='modeltesttemplatecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_test_template_configurations', to='api.category'),
        ),
        migrations.AddField(
            model_name='modeltesttemplatecategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_configurations', to='api.modeltesttemplate'),
        ),
        migrations.AddConstraint(
            model_name='modeltesttemplatecategory',
            constraint=models.UniqueConstraint(fields=('template', 'category'), name='unique_template_category'),
        ),
        migrations.AddConstraint(
            model_name='modeltesttemplatecategory',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gt', 0)), name='mttc_question_count_positive'),
        ),
    ]
