# Generated by Django 5.2.5 on 2026-07-16 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_modeltesttemplatecategory_quiz_correct_mark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'level', 'order'], name='cat_parent_level_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'order', 'name'], name='cat_level_order_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_type', 'category'], name='quiz_type_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['generated_for_user', 'generated_for_guest', 'quiz_type'], name='quiz_owner_type_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_at'], name='quiz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'is_completed', 'start_time'], name='attempt_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['guest_user', 'is_completed', 'start_time'], name='attempt_guest_state_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'is_completed'], name='attempt_quiz_state_idx'),
        ),
        migrations.AddIndex(
            model_name='quizcategory',
            index=models.Index(fields=['parent', 'level', 'order'], name='quizcat_parent_level_idx'),
        ),
        migrations.AddIndex(
            model_name='quizcategory',
            index=models.Index(fields=['level', 'order', 'name'], name='quizcat_level_order_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquestion',
            index=models.Index(fields=['user', 'question'], name='saved_user_question_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquestion',
            index=models.Index(fields=['guest_user', 'question'], name='saved_guest_question_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquestion',
            index=models.Index(fields=['saved_at'], name='saved_at_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubmission',
            index=models.Index(fields=['attempt', 'is_correct'], name='submission_attempt_ok_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubmission',
            index=models.Index(fields=['question'], name='submission_question_idx'),
        ),
    ]
