# Generated by Django 5.2.5 on 2026-07-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_cat_parent_level_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('latest_version', models.CharField(max_length=32)),
                ('latest_build_number', models.PositiveIntegerField()),
                ('minimum_supported_build_number', models.PositiveIntegerField(default=1)),
                ('force_update', models.BooleanField(default=False)),
                ('title', models.CharField(default='New update available', max_length=120)),
                ('message', models.TextField(default='Update now for the latest improvements.')),
                ('release_notes', models.JSONField(blank=True, default=list)),
                ('update_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Update Config',
                'verbose_name_plural': 'App Update Configs',
                'ordering': ['platform', '-latest_build_number'],
                'indexes': [models.Index(fields=['platform', 'is_active', '-latest_build_number'], name='app_update_lookup_idx')],
            },
        ),
    ]
