# Generated by Django 5.2.5 on 2026-08-04 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appupdateconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'id'], name='answer_question_id_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'is_correct'], name='answer_question_ok_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprogress',
            index=models.Index(fields=['user', 'date'], name='dprogress_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprogress',
            index=models.Index(fields=['guest_user', 'date'], name='dprogress_guest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprogress',
            index=models.Index(fields=['user', 'target_type', 'date'], name='dprogress_user_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprogress',
            index=models.Index(fields=['guest_user', 'target_type', 'date'], name='dprogress_gst_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytarget',
            index=models.Index(fields=['user', 'is_active'], name='dtarget_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytarget',
            index=models.Index(fields=['guest_user', 'is_active'], name='dtarget_guest_active_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytarget',
            index=models.Index(fields=['user', 'target_type'], name='dtarget_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytarget',
            index=models.Index(fields=['guest_user', 'target_type'], name='dtarget_guest_type_idx'),
        ),
        migrations.AddIndex(
            model_name='guestuser',
            index=models.Index(fields=['last_active'], name='guest_last_active_idx'),
        ),
        migrations.AddIndex(
            model_name='guestuser',
            index=models.Index(fields=['created_at'], name='guest_created_idx'),
        ),
        migrations.AddIndex(
            model_name='modeltesttemplate',
            index=models.Index(fields=['is_active', 'display_order', 'name'], name='mtt_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='modeltesttemplatecategory',
            index=models.Index(fields=['template', 'order'], name='mttc_template_order_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'id'], name='question_cat_id_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='question_created_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['updated_at'], name='question_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='questionreport',
            index=models.Index(fields=['status', 'reported_at'], name='qreport_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='questionreport',
            index=models.Index(fields=['question', 'status'], name='qreport_question_idx'),
        ),
        migrations.AddIndex(
            model_name='questionreport',
            index=models.Index(fields=['user', 'reported_at'], name='qreport_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['user', 'target_type'], name='streak_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['guest_user', 'target_type'], name='streak_guest_type_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_date'], name='activity_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['guest_user', 'activity_date'], name='activity_guest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type', 'activity_date'], name='activity_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['guest_user', 'activity_type', 'activity_date'], name='activity_guest_type_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_time'], name='activity_time_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogress',
            index=models.Index(fields=['user', 'week_start_date'], name='wprogress_user_week_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogress',
            index=models.Index(fields=['guest_user', 'week_start_date'], name='wprogress_guest_week_idx'),
        ),
    ]
