# Generated by Django 5.2.5 on 2026-09-21 07:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0012_answer_answer_question_id_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.question')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupStudyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='group_study.groupstudyquestion')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupStudyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('correct_mark', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('wrong_mark', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('0'))])),
                ('unanswered_mark', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('0'))])),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_study_quizzes', to=settings.AUTH_USER_MODEL)),
                ('source_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.quiz')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='groupstudyquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='group_study.groupstudyquiz'),
        ),
        migrations.CreateModel(
            name='GroupStudyQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wrong_mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unanswered_mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='group_study.groupstudyquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_study_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupStudyQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='group_study.groupstudyquizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='group_study.groupstudyquestion')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_in_submissions', to='group_study.groupstudyanswer')),
            ],
            options={
                'ordering': ['question__position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='groupstudyquiz',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='group_study.studygroup'),
        ),
        migrations.CreateModel(
            name='StudyGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='group_study.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='groupstudyanswer',
            index=models.Index(fields=['question', 'position'], name='group_answer_question_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyanswer',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='unique_group_answer_position'),
        ),
        migrations.AddIndex(
            model_name='groupstudyquestion',
            index=models.Index(fields=['quiz', 'position'], name='group_question_quiz_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'position'), name='unique_group_question_position'),
        ),
        migrations.AddIndex(
            model_name='groupstudyquizattempt',
            index=models.Index(fields=['user', 'is_completed', 'start_time'], name='group_attempt_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstudyquizattempt',
            index=models.Index(fields=['quiz', 'is_completed', 'start_time'], name='group_attempt_quiz_state_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstudyquizattempt',
            index=models.Index(fields=['quiz', 'user', 'is_completed'], name='group_attempt_quiz_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False)), fields=('user', 'quiz'), name='unique_active_group_attempt'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('total_questions__gt', 0)), name='group_attempt_total_positive'),
        ),
        migrations.AddIndex(
            model_name='groupstudyquizsubmission',
            index=models.Index(fields=['attempt', 'is_correct'], name='group_submit_att_ok_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstudyquizsubmission',
            index=models.Index(fields=['question'], name='group_submit_question_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquizsubmission',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_group_attempt_question_submission'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['created_by', 'created_at'], name='group_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['is_active', 'name', 'id'], name='group_state_name_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstudyquiz',
            index=models.Index(fields=['group', 'is_published', 'start_at'], name='group_quiz_state_start_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstudyquiz',
            index=models.Index(fields=['start_at', 'end_at'], name='group_quiz_window_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquiz',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='group_quiz_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquiz',
            constraint=models.CheckConstraint(condition=models.Q(('correct_mark__gte', 0)), name='group_quiz_correct_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquiz',
            constraint=models.CheckConstraint(condition=models.Q(('wrong_mark__lte', 0)), name='group_quiz_wrong_nonpositive'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquiz',
            constraint=models.CheckConstraint(condition=models.Q(('unanswered_mark__lte', 0)), name='group_quiz_unanswered_nonpositive'),
        ),
        migrations.AddConstraint(
            model_name='groupstudyquiz',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='group_quiz_window_valid'),
        ),
        migrations.AddIndex(
            model_name='studygroupmembership',
            index=models.Index(fields=['user', 'group'], name='membership_user_group_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroupmembership',
            index=models.Index(fields=['group', 'role'], name='membership_group_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='studygroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_study_group_membership'),
        ),
    ]
