# Generated by Django 5.2.8 on 2026-09-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_study', '0003_studygrouppmembership_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroupmembership',
            name='notify_messages',
            field=models.BooleanField(default=True),
        ),
    ]
