# Generated by Django 5.2.8 on 2026-09-22 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_answer_answer_question_id_idx_and_more'),
        ('group_study', '0004_studygroupmembership_notify_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members_can_create_quizzes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='groupstudyquiz',
            index=models.Index(fields=['group', '-created_at'], name='group_quiz_group_created_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['is_public', 'name', 'id'], name='group_public_name_idx'),
        ),
    ]
