# Generated by Django 5.2.8 on 2026-07-31 10:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('source_question_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_question_url', models.URLField(blank=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('course_type', models.CharField(choices=[('ARCHIVE', 'Archive'), ('LIVE', 'Live')], default='ARCHIVE', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('allow_self_enrollment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('STAFF', 'Staff'), ('SELF', 'Self')], default='STAFF', max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.coursequestion')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quiz_type', models.CharField(choices=[('PRACTICE', 'Practice'), ('MODEL_TEST', 'Model Test'), ('QUESTION_BANK', 'Question Bank')], default='PRACTICE', max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('correct_mark', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('wrong_mark', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('0'))])),
                ('unanswered_mark', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('0'))])),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_name', models.CharField(blank=True, default='', max_length=50)),
                ('external_quiz_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.coursequiz'),
        ),
        migrations.CreateModel(
            name='CourseQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wrong_mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unanswered_mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='courses.coursequiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.coursequizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='courses.coursequestion')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_in_submissions', to='courses.courseanswer')),
            ],
            options={
                'ordering': ['question__position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'course_type', 'created_at'], name='course_state_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_by', 'created_at'], name='course_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'is_active'], name='course_enroll_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'is_active'], name='course_enroll_course_state_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['enrolled_at'], name='course_enroll_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_enrollment'),
        ),
        migrations.AddIndex(
            model_name='courseanswer',
            index=models.Index(fields=['question', 'position'], name='course_answer_question_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseanswer',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='unique_course_answer_position'),
        ),
        migrations.AddIndex(
            model_name='coursequiz',
            index=models.Index(fields=['course', 'is_active', 'position'], name='crs_quiz_state_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequiz',
            index=models.Index(fields=['course', 'is_active', 'unlock_at'], name='crs_quiz_unlock_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequiz',
            index=models.Index(fields=['course', 'source_name', 'external_quiz_id'], name='crs_quiz_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursequiz',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='unique_course_quiz_position'),
        ),
        migrations.AddConstraint(
            model_name='coursequiz',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_name', ''), _negated=True), models.Q(('external_quiz_id', ''), _negated=True)), fields=('course', 'source_name', 'external_quiz_id'), name='unique_course_quiz_external_source'),
        ),
        migrations.AddConstraint(
            model_name='coursequiz',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='course_quiz_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='coursequiz',
            constraint=models.CheckConstraint(condition=models.Q(('correct_mark__gte', 0)), name='course_quiz_correct_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='coursequiz',
            constraint=models.CheckConstraint(condition=models.Q(('wrong_mark__lte', 0)), name='course_quiz_wrong_nonpositive'),
        ),
        migrations.AddConstraint(
            model_name='coursequiz',
            constraint=models.CheckConstraint(condition=models.Q(('unanswered_mark__lte', 0)), name='course_quiz_unanswered_nonpositive'),
        ),
        migrations.AddIndex(
            model_name='coursequestion',
            index=models.Index(fields=['quiz', 'position'], name='course_question_quiz_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequestion',
            index=models.Index(fields=['quiz', 'fingerprint'], name='course_question_quiz_fp_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursequestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'position'), name='unique_course_question_position'),
        ),
        migrations.AddConstraint(
            model_name='coursequestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'fingerprint'), name='unique_course_question_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='coursequestion',
            constraint=models.UniqueConstraint(condition=models.Q(('source_question_id', ''), _negated=True), fields=('quiz', 'source_question_id'), name='unique_course_question_external_id'),
        ),
        migrations.AddIndex(
            model_name='coursequizattempt',
            index=models.Index(fields=['user', 'is_completed', 'start_time'], name='course_attempt_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequizattempt',
            index=models.Index(fields=['quiz', 'is_completed', 'start_time'], name='course_attempt_quiz_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursequizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False)), fields=('user', 'quiz'), name='unique_active_course_attempt'),
        ),
        migrations.AddConstraint(
            model_name='coursequizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('total_questions__gt', 0)), name='course_attempt_total_positive'),
        ),
        migrations.AddIndex(
            model_name='coursequizsubmission',
            index=models.Index(fields=['attempt', 'is_correct'], name='crs_submit_att_ok_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequizsubmission',
            index=models.Index(fields=['question'], name='crs_submit_question_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursequizsubmission',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_course_attempt_question_submission'),
        ),
    ]
