# Generated by Django 5.2.5 on 2026-08-04 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursequiz_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'name', 'id'], name='course_pub_name_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'is_active', 'enrolled_at'], name='crs_enr_user_state_at_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequiz',
            index=models.Index(fields=['is_active', 'position', 'id'], name='crs_quiz_active_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequizattempt',
            index=models.Index(fields=['quiz', 'user', 'is_completed'], name='crs_att_quiz_user_state_idx'),
        ),
    ]
