# Generated by Django 5.2.8 on 2026-08-04 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appupdateconfig'),
        ('courses', '0002_coursequiz_topic'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast')], default='manual', max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('route', models.CharField(blank=True, default='', help_text='Optional in-app route the notification should open when tapped.', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Extra tap-target data, e.g. {"course_id": 12}.')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast')], max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Turn this automated notification on or off.')),
                ('title_template', models.CharField(blank=True, default='', help_text='Notification title. Leave blank to use the built-in default.', max_length=120)),
                ('message_template', models.TextField(blank=True, default='', help_text='Notification body. Leave blank to use the built-in default. Inactivity reminders may append a question when enabled below.')),
                ('inactivity_days', models.PositiveIntegerField(default=2, help_text='Inactivity reminder only: days without activity before reminding.')),
                ('include_question', models.BooleanField(default=True, help_text='Inactivity reminder only: append a random practice question.')),
                ('send_hour_utc', models.PositiveIntegerField(default=3, help_text='Hour of day (UTC, 0-23) this automation is allowed to run.', validators=[django.core.validators.MaxValueValidator(23)])),
                ('new_course_lookback_hours', models.PositiveIntegerField(default=24, help_text='New course launch only: how far back to look for new published courses.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Automation',
                'verbose_name_plural': 'Notification Automations',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast')], max_length=32)),
                ('dedupe_key', models.CharField(max_length=190)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Delivery',
                'verbose_name_plural': 'Notification Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('course', 'Learners enrolled in a course'), ('inactive', 'Inactive learners')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Required when the audience is "Learners enrolled in a course".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_campaigns', to='courses.course'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Set a future time and status "Scheduled" to have cron send this automatically. Leave blank to send manually.', null=True),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='campaign_status_sched_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationcampaign'),
        ),
        migrations.AddField(
            model_name='notification',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('kind', 'dedupe_key'), name='unique_notification_delivery'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['guest_user', 'is_read', '-created_at'], name='notif_guest_unread_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='notification_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='notification_cannot_have_both_user_and_guest'),
        ),
    ]
