# Generated by Django 5.2.8 on 2026-08-04 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appupdateconfig'),
        ('notifications', '0002_notification_notificationautomation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationautomation',
            name='default_questions_per_day',
            field=models.PositiveIntegerField(default=3, help_text='Daily MCQ only: default number of questions for new subscribers. Each subscriber can change their own count (1-8).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast'), ('daily_mcq', 'Daily MCQ subscription')], default='manual', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationautomation',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast'), ('daily_mcq', 'Daily MCQ subscription')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast'), ('daily_mcq', 'Daily MCQ subscription')], default='manual', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast'), ('daily_mcq', 'Daily MCQ subscription')], max_length=32),
        ),
        migrations.CreateModel(
            name='DailyMcqSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('questions_per_day', models.PositiveIntegerField(default=3, help_text='How many MCQs to deliver each day (1-8).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_mcq_subscription', to='api.guestuser')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_mcq_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily MCQ Subscription',
                'verbose_name_plural': 'Daily MCQ Subscriptions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_active'], name='mcq_subscription_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='mcq_subscription_must_have_user_or_guest'), models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='mcq_subscription_cannot_have_both_user_and_guest'), models.CheckConstraint(condition=models.Q(('questions_per_day__gte', 1), ('questions_per_day__lte', 8)), name='mcq_subscription_questions_per_day_range')],
            },
        ),
    ]
