# Generated by Django 5.2.8 on 2026-08-04 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appupdateconfig'),
        ('notifications', '0003_notificationautomation_default_questions_per_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMcqDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_date', models.DateField()),
                ('slot', models.PositiveIntegerField(help_text='Which delivery slot of the day this question was sent in.')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily MCQ Delivery',
                'verbose_name_plural': 'Daily MCQ Deliveries',
                'ordering': ['-delivered_date', '-slot', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='dailymcqsubscription',
            name='mcq_subscription_questions_per_day_range',
        ),
        migrations.AlterField(
            model_name='dailymcqsubscription',
            name='questions_per_day',
            field=models.PositiveIntegerField(default=3, help_text='How many MCQs to deliver each day (1-12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='notificationautomation',
            name='default_questions_per_day',
            field=models.PositiveIntegerField(default=3, help_text='Daily MCQ only: default number of questions for new subscribers. Each subscriber can change their own count (1-12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddConstraint(
            model_name='dailymcqsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('questions_per_day__gte', 1), ('questions_per_day__lte', 12)), name='mcq_subscription_questions_per_day_range'),
        ),
        migrations.AddField(
            model_name='dailymcqdelivery',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_mcq_deliveries', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='dailymcqdelivery',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_mcq_deliveries', to='api.question'),
        ),
        migrations.AddField(
            model_name='dailymcqdelivery',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_mcq_selections', to='api.answer'),
        ),
        migrations.AddField(
            model_name='dailymcqdelivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_mcq_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailymcqdelivery',
            index=models.Index(fields=['user', 'delivered_date'], name='mcq_delivery_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymcqdelivery',
            index=models.Index(fields=['guest_user', 'delivered_date'], name='mcq_delivery_guest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymcqdelivery',
            index=models.Index(fields=['delivered_date', 'is_correct'], name='mcq_delivery_date_correct_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailymcqdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='mcq_delivery_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailymcqdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='mcq_delivery_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailymcqdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'delivered_date', 'slot'), name='unique_user_mcq_delivery_slot'),
        ),
        migrations.AddConstraint(
            model_name='dailymcqdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'delivered_date', 'slot'), name='unique_guest_mcq_delivery_slot'),
        ),
    ]
