# Generated by Django 5.2.8 on 2026-08-06 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_dailymcqdelivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationautomation',
            name='send_hour_utc',
        ),
        migrations.AddField(
            model_name='notificationautomation',
            name='daytime_end_hour',
            field=models.PositiveIntegerField(default=22, help_text="Local hour (Asia/Dhaka, 0-23) after which sending stops, e.g. 22 for 10 PM. Daily MCQ also spreads each subscriber's questions evenly across this window instead of sending one per hour.", validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='notificationautomation',
            name='daytime_start_hour',
            field=models.PositiveIntegerField(default=8, help_text='Local hour (Asia/Dhaka, 0-23) notifications may start sending, e.g. 8 for 8 AM. Shared by every automation so nothing fires overnight.', validators=[django.core.validators.MaxValueValidator(23)]),
        ),
    ]
