# Generated by Django 5.2.5 on 2026-09-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notificationautomation_send_hour_utc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast'), ('daily_mcq', 'Daily MCQ subscription'), ('group_study_added', 'Added to a study group'), ('group_study_publish', 'New group study quiz published'), ('group_study_reminder', 'Group study schedule reminder')], default='manual', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationautomation',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast'), ('daily_mcq', 'Daily MCQ subscription'), ('group_study_added', 'Added to a study group'), ('group_study_publish', 'New group study quiz published'), ('group_study_reminder', 'Group study schedule reminder')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast'), ('daily_mcq', 'Daily MCQ subscription'), ('group_study_added', 'Added to a study group'), ('group_study_publish', 'New group study quiz published'), ('group_study_reminder', 'Group study schedule reminder')], default='manual', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual broadcast'), ('inactivity_reminder', 'Daily inactivity reminder'), ('course_announcement', 'Enrolled course announcement'), ('new_course_launch', 'New course launch'), ('scheduled_broadcast', 'Scheduled broadcast'), ('daily_mcq', 'Daily MCQ subscription'), ('group_study_added', 'Added to a study group'), ('group_study_publish', 'New group study quiz published'), ('group_study_reminder', 'Group study schedule reminder')], max_length=32),
        ),
    ]
